=== DoekeleR/klic-win/Uitleveren/Leveringsinformatie/LeveringsInfo-2.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2013 rel. 2 sp2 (http://www.altova.com) by Kadaster (Kadaster) -->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:levi="http://www.kadaster.nl/schemas/klic/20080722/leveringsinfo" xmlns:levs="http://www.kadaster.nl/schemas/20080722/levinfo" xmlns:gml="http://www.opengis.net/gml" targetNamespace="http://www.kadaster.nl/schemas/klic/20080722/leveringsinfo" elementFormDefault="qualified" version="2.0">
	<xsd:annotation>
		<xsd:documentation>Versie  : 2.0
Datum :  06-07-2016
N.a.v. ondersteuning IMKL2015-features 
</xsd:documentation>
	</xsd:annotation>
	<xsd:import namespace="http://www.opengis.net/gml" schemaLocation="../gml/3.1.1./base/gml.xsd"/>
	<xsd:import namespace="http://www.kadaster.nl/schemas/20080722/levinfo" schemaLocation="LeveringsInfoSimpleTypes-2.0.xsd"/>
	<xsd:element name="Leveringsinformatie" type="levi:LeveringsinformatieType">
		<xsd:annotation>
			<xsd:documentation>Leveringsinformatie t.b.v. Klic-viewers.</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="LeveringsinformatieType">
		<xsd:annotation>
			<xsd:documentation>(Meta)gegevens van de geleverde informatie t.b.v. Klic-viewers.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Version" type="levs:VersionNumberType">
				<xsd:annotation>
					<xsd:documentation>Versie van het interface waarmee de leveringsinformatie wordt beschreven</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Aanvraag" type="levi:AanvraagType">
				<xsd:annotation>
					<xsd:documentation>Enkele kenmerkende gegevens van de gebiedsinformatie-aanvraag.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Leveringsvolgnummer" type="levs:LeveringsVolgnummerType">
				<xsd:annotation>
					<xsd:documentation>Volgnummer van de levering (binnen de aanvraag). Indfien de aanvraag in meerdere keren wordt opgeleverd (bijv. omdat 1 of meer netbeheerders te laat leveren) wordt dit nummer steeds opgehoogd.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="IndicatieLeveringCompleet" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>Indicator die aangeeft of de levering compleet is (dus, of alle netbeheerders al hebben geleverd).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Leveringsbrief" type="levi:PdfBestandType">
				<xsd:annotation>
					<xsd:documentation>Opgemaakte leveringsbrief met een beschrijving van en toelichting op de geleverde producten.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ondergrondkaarten" type="levi:OndergrondkaartType" minOccurs="0" maxOccurs="2">
				<xsd:annotation>
					<xsd:documentation>Een lijst met door Kadaster aangeleverde ondergrondkaart(en) in png-formaat (grootschalige (plan)topografie).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="GebundeldeNetinformatie" type="levi:XmlBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Xml-bestand waarbij alle door de netbeheerders volgens IMKL2015 aangeleverde netinformatie is gebundeld.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="NetbeheerderLeveringen" type="levi:NetbeheerderLeveringType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Een lijst met door belanghebbende netbeheerders aangeleverde beheerdersinformatie.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AanvraagType">
		<xsd:annotation>
			<xsd:documentation>Set van gegevens inzake de gebiedsinformatie-aanvraag.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Klicnummer" type="levs:KlicnummerType">
				<xsd:annotation>
					<xsd:documentation>Klic-meldnummer, de logische identificatie van de Klic-melding zoals deze binnen de graafsector bekend is.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ordernummer" type="levs:OrdernummerType">
				<xsd:annotation>
					<xsd:documentation>Ordernummer van de verkooporder waaronder de aanvraag binnen KLIC bekend is.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Positienummer" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Het regelnummer van de verkooporder waaronder de aanvraag binnen KLIC bekend is.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="RelatienummerAanvrager" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Het unieke klantnummer waaronder de aanvrager (grondroerder) binnen het Kadaster geregistreerd staat.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Meldingsoort" type="levs:MeldingsoortType">
				<xsd:annotation>
					<xsd:documentation>Soort aanvraag: graafmelding, orientatieverzoek of een calamiteitenmelding</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="DatumTijdAanvraag" type="levs:DatumTijdType">
				<xsd:annotation>
					<xsd:documentation>Datum en tijdstip waarop de gebiedsinformatie-aanvraag door de aanvrager bij KLIC is aangeboden.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="KlantReferentie" type="levs:KlantReferentieType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Eigen referentie die de klant aan de aanvraag heeft gegeven.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Gebiedspolygoon" type="gml:PolygonType">
				<xsd:annotation>
					<xsd:documentation>Polygoon dit het gebied aanduidt waarvoor netinformatie wordt gevraagd, omdat er (mogelijk in de toekomst) gegraven gaat worden.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Informatiepolygoon" type="gml:PolygonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Polygoon dit het ruimere gebied aanduidt waarvoor aanvullende netinformatie wordt gevraagd.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="GeselecteerdGebiedKaart" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Kaart met het geselecteerde gebied waarvoor netinformatie wordt gevraagd.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Pngformaat" type="levi:PngFormaatType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Geeft het formaat aan waaraan de geleverde png-bestanden moeten voldoen.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ontvangstbevestiging" type="levi:PdfBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>De ontvangstbevestiging, zoals deze oorspronkelijk is opgesteld voor de aanvraag.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NetbeheerderLeveringType">
		<xsd:annotation>
			<xsd:documentation>Gegevens van één netbeheerder welke meegeleverd worden in de leveringsinformatie.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Netbeheerder" type="levi:NetbeheerderType">
				<xsd:annotation>
					<xsd:documentation>Stamgegevens van de netbeheerder. Sommige contactgegevens zijn in IMKL2015 niet meer beschikbaar.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BetrokkenBijAanvraag" type="levs:BetrokkenBijAanvraagType">
				<xsd:annotation>
					<xsd:documentation>Indicatie die aangeeft of de netbeheerder binnen de gevraagde polygoon kabel- of leidinginformatie heeft.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Netinformatie" type="levi:XmlBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Xml-bestand van de door de netbeheerder volgens IMKL2015 aangeleverde netinformatie.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Themas" type="levi:LeveringThemaType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Alle door de netbeheerder bij een thema aangeleverde beheerdersinformatie.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Bijlagen" type="levi:AlgemeneBijlageType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Algemene bijlagen van de netbeheerder</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ondergrondkaarten" type="levi:OndergrondkaartType" minOccurs="0" maxOccurs="2">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Kaarten met eigen topografie van de netbeheerder in png-formaat (EigenTopo, PlanTopo).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<!--		<xsd:element name="EigenTopo" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Kaart met eigen topografie van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="PlanTopo" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Kaart met eigen plantopografie van de netbeheerder</xsd:documentation>
				</xsd:annotation>
			</xsd:element> -->
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="NetbeheerderType">
		<xsd:annotation>
			<xsd:documentation>Stamgegevens van een netbeheerder.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Bronhoudercode" type="levs:BronhoudercodeType">
				<xsd:annotation>
					<xsd:documentation>Bronhoudercode van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="RelatienummerNetbeheerder" type="levs:RelatienummerType">
				<xsd:annotation>
					<xsd:documentation>Unieke identificatie van de netbeheerder als zakenrelatie van het Kadaster.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Bedrijfsnaam" type="levs:NaamType">
				<xsd:annotation>
					<xsd:documentation>Bedrijfsnaam van de netbeheerder (uit Relatiebeheer).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="BedrijfsnaamAfkorting" type="levs:NaamType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Afkorting van de naam van de netbeheerder zoals gebruikt in de naamgeving van de thema- bestanden.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Contact" type="levi:ContactType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Contactpersoon van de netbeheerder afkomstig uit de beheerdersinformatie.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Contactpersoon" type="levi:ContactpersoonType">
				<xsd:annotation>
					<xsd:documentation>Contactpersoon van de netbeheerder afkomstig uit Relatiebeheer.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Storingsnummer" type="levs:TelefoonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Algemeen storingsnummer van de netbeheerder dan wel een bepaalde groep van netbeheerders. 
(* Alleen verplicht voor beheerders van buisleidingen met gevaarlijke inhoud)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Beschadigingsnummer" type="levs:TelefoonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Nummer van de netbeheerder dat gebeld moet worden indien er sprake is van schade, zonder dat de levering is onderbroken (Bijv. alleen mantel stuk)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ContactpersoonType">
		<xsd:annotation>
			<xsd:documentation>Contactpersoon van de netbeheerder.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Naam" type="levs:NaamType">
				<xsd:annotation>
					<xsd:documentation>Naam van de contactpersoon van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Telefoon" type="levs:TelefoonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Telefoon van de contactpersoon van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Email" type="levs:EmailType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>E-mailadres van de contactpersoon van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Fax" type="levs:TelefoonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Faxnummer van de contactpersoon van de netbeheerder.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ContactType">
		<xsd:annotation>
			<xsd:documentation>Contact van de netbeheerder</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Naam" type="levs:NaamType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Naam van het contact</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Telefoon" type="levs:TelefoonType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Telefoonnummer van het contact</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Email" type="levs:EmailType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>E-mailadres van het contact</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="LeveringThemaType">
		<xsd:annotation>
			<xsd:documentation>Door een netbeheerder geleverde informatie voor een thema</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Thema" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Thema van de door de netbeheerder geleverde informatie (IMKL2015)</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Themanaam" type="levs:ThemaNaamType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Themanaam (zie enumeratie) van de door de netbeheerder geleverde informatie.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Toezichthouders" type="levi:ContactType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>[Klic5] Lijst van toezichthouders van de netbeheerder voor dit thema.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="EisVoorzorgmaatregel" type="levs:EisVoorzorgmaatregelType">
				<xsd:annotation>
					<xsd:documentation>Indicator die aangeeft of er een eis/voorzorgmaatregel bij dit thema is gevoegd</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ligging" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5]</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Maatvoering" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5]</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Annotatie" type="levi:PngBestandType" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>[Klic5]</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<!--			<xsd:element name="Detailkaarten" type="levi:DetailkaartenType" minOccurs="0"/> -->
			<!--			<xsd:element name="Huisaansluitschetsen" type="levi:HuisaansluitschetsbestandenType" minOccurs="0"/> -->
			<xsd:element name="ThemaBijlagen" type="levi:ThemaBijlageType" minOccurs="0" maxOccurs="unbounded">
				<xsd:annotation>
					<xsd:documentation>Themabijlagen van de netbeheerder</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="XmlBestandType">
		<xsd:sequence>
			<xsd:element name="Bestandsnaam" type="levs:BestandsnaamType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PdfBestandType">
		<xsd:sequence>
			<xsd:element name="Bestandsnaam" type="levs:BestandsnaamType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PngBestandType">
		<xsd:annotation>
			<xsd:documentation>[Klic5]</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="Bestandsnaam" type="levs:BestandsnaamType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="AlgemeneBijlageType">
		<xsd:annotation>
			<xsd:documentation>Door een netbeheerder aangeleverde algemene bijlage.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SoortBijlage" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Soort algemene bijlage (bijv. BL, algemeen, nietBetrokken).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Bijlage" type="levi:PdfBestandType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="ThemaBijlageType">
		<xsd:annotation>
			<xsd:documentation>Door een netbeheerder aangeleverde themagebonden bijlage (ExtraDetailInfo of eisVoorzorgsmaatregel).</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SoortThemaBijlage" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Soort thema bijlage (bijv. HA/DK/TB/EV, huisaansluiting, aansluiting, profielschets, verzoekTotContact, overig, eisVoorzorgsmaatregel).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Adres" type="xsd:string" minOccurs="0">
				<xsd:annotation>
					<xsd:documentation>Adresaanduiding bij huisaansluiting</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Bijlage" type="levi:PdfBestandType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="OndergrondkaartType">
		<xsd:annotation>
			<xsd:documentation>Ondergrondkaart met grootschalige topografie (bestaand of plan) in png-formaat.</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="SoortOndergrondkaart" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>Soort ondergrondkaart (Kadaster: bgtBestaand/bgtPlan; netbeheerder: eigenTopoBestaand/eigenTopoPlan).</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="Ondergrondkaart" type="levi:PngBestandType"/>
		</xsd:sequence>
	</xsd:complexType>
	<xsd:complexType name="PngFormaatType">
		<xsd:annotation>
			<xsd:documentation>Wordt gebruikt om richting netbeheerder aan te geven wat het preciese forrmaat van het kaartmateriaal moet zijn dat hij gaat leveren</xsd:documentation>
		</xsd:annotation>
		<xsd:sequence>
			<xsd:element name="OmsluitendeRechthoek" type="gml:BoundingShapeType">
				<xsd:annotation>
					<xsd:documentation>Rechthoek (GML definitie) die de getekende polygoon omsluit. Bepaalt het gebied waarover de png-kaarten moeten worden geleverd.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="PixelsBreed" type="levs:AantalPixelsType">
				<xsd:annotation>
					<xsd:documentation>Geeft de breedte (in pixels) aan van de op te leveren png kaarten.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
			<xsd:element name="PixelsHoog" type="levs:AantalPixelsType">
				<xsd:annotation>
					<xsd:documentation>Geeft de hoogte (in pixels) aan van de op te leveren png kaarten.</xsd:documentation>
				</xsd:annotation>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>
</xsd:schema>

=== DoekeleR/klic-win/Uitleveren/Leveringsinformatie/LI_15G357840_1 (versie 2.0 2016-07-26).xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<lev:Leveringsinformatie xmlns:lev="http://www.kadaster.nl/schemas/klic/20080722/leveringsinfo" xmlns:gml="http://www.opengis.net/gml" xmlns:ns3="http://www.w3.org/1999/xlink" xmlns:ns4="http://www.w3.org/2001/SMIL20/" xmlns:ns5="http://www.w3.org/2001/SMIL20/Language" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.kadaster.nl/schemas/klic/20080722/leveringsinfo file:///U:/Services/RVTs/KLIC/Systeemdocumentatie/75%20Interface%20specificaties/DomeinKlic/Leveringsinformatie/LeveringsInfo-2.0.xsd">
	<lev:Version>2.0</lev:Version>
	<lev:Aanvraag>
		<lev:Klicnummer>15G357840</lev:Klicnummer>
		<lev:Ordernummer>9806502397</lev:Ordernummer>
		<lev:Positienummer>10</lev:Positienummer>
		<lev:RelatienummerAanvrager>0000648756</lev:RelatienummerAanvrager>
		<lev:Meldingsoort>Graafmelding</lev:Meldingsoort>
		<lev:DatumTijdAanvraag>2015-09-28T08:33:16.000+02:00</lev:DatumTijdAanvraag>
		<lev:KlantReferentie>Mijn ref.: 2016-07-19 versie 2.0</lev:KlantReferentie>
		<lev:Gebiedspolygoon srsName="epsg:28992" srsDimension="2" axisLabels="x y" uomLabels="m m">
			<gml:exterior>
				<gml:LinearRing>
					<gml:posList>117395 487103 117391 487061 117534 487027 117659 486997 117785 486977 117830 486980 117833 487014 117689 487024 117597 487044 117496 487072 117395 487103</gml:posList>
				</gml:LinearRing>
			</gml:exterior>
		</lev:Gebiedspolygoon>
		<lev:Informatiepolygoon srsName="epsg:28992" srsDimension="2" axisLabels="x y" uomLabels="m m">
			<gml:exterior>
				<gml:LinearRing>
					<gml:posList>117395 487103 117391 487061 117534 487027 117659 486997 117785 486977 117830 486980 117833 487014 117689 487024 117597 487044 117496 487072 117395 487103</gml:posList>
				</gml:LinearRing>
			</gml:exterior>
		</lev:Informatiepolygoon>
		<lev:GeselecteerdGebiedKaart>
			<lev:Bestandsnaam>bronnen/SEL_15G357840.png</lev:Bestandsnaam>
		</lev:GeselecteerdGebiedKaart>
		<lev:Pngformaat>
			<lev:OmsluitendeRechthoek>
				<gml:Envelope srsName="epsg:28992" srsDimension="2" axisLabels="x y" uomLabels="m m">
					<gml:lowerCorner>117391 486977</gml:lowerCorner>
					<gml:upperCorner>117833 487103</gml:upperCorner>
				</gml:Envelope>
			</lev:OmsluitendeRechthoek>
			<lev:PixelsBreed>6188</lev:PixelsBreed>
			<lev:PixelsHoog>1764</lev:PixelsHoog>
		</lev:Pngformaat>
		<lev:Ontvangstbevestiging>
			<lev:Bestandsnaam>Ontvangstbevestiging_15G357840.pdf</lev:Bestandsnaam>
		</lev:Ontvangstbevestiging>
	</lev:Aanvraag>
	<lev:Leveringsvolgnummer>1</lev:Leveringsvolgnummer>
	<lev:IndicatieLeveringCompleet>true</lev:IndicatieLeveringCompleet>
	<lev:Leveringsbrief>
		<lev:Bestandsnaam>LI_15G357840_1.pdf</lev:Bestandsnaam>
	</lev:Leveringsbrief>
	<lev:Ondergrondkaarten>
		<lev:SoortOndergrondkaart>bgtBestaand</lev:SoortOndergrondkaart>
		<lev:Ondergrondkaart>
			<lev:Bestandsnaam>bronnen/GB_15G357840.png</lev:Bestandsnaam>
		</lev:Ondergrondkaart>
	</lev:Ondergrondkaarten>
	<lev:Ondergrondkaarten>
		<lev:SoortOndergrondkaart>bgtPlan</lev:SoortOndergrondkaart>
		<lev:Ondergrondkaart>
			<lev:Bestandsnaam>bronnen/GP_15G357840.png</lev:Bestandsnaam>
		</lev:Ondergrondkaart>
	</lev:Ondergrondkaarten>
	<lev:GebundeldeNetinformatie>
		<lev:Bestandsnaam>NI_netinformatie_15G357840_1</lev:Bestandsnaam>
	</lev:GebundeldeNetinformatie>
	<lev:NetbeheerderLeveringen>
		<lev:Netbeheerder>
			<lev:Bronhoudercode>KL0002</lev:Bronhoudercode>
			<lev:RelatienummerNetbeheerder>0000574962</lev:RelatienummerNetbeheerder>
			<lev:Bedrijfsnaam>Liander</lev:Bedrijfsnaam>
			<lev:BedrijfsnaamAfkorting>Liander</lev:BedrijfsnaamAfkorting>
			<lev:Contact>
				<lev:Telefoon>0611 382 570</lev:Telefoon>
			</lev:Contact>
			<lev:Contactpersoon>
				<lev:Naam>Gis Data Klic</lev:Naam>
				<lev:Telefoon>0611382570</lev:Telefoon>
				<lev:Email>infoklic@alliander.com</lev:Email>
			</lev:Contactpersoon>
			<lev:Storingsnummer>0800-9009</lev:Storingsnummer>
		</lev:Netbeheerder>
		<lev:BetrokkenBijAanvraag>true</lev:BetrokkenBijAanvraag>
		<lev:Netinformatie>
			<lev:Bestandsnaam>bronnen/KL0002/NI_netinformatie_KL0002_15G357840.xml</lev:Bestandsnaam>
		</lev:Netinformatie>
		<lev:Themas>
			<lev:Thema>gasHogeDruk</lev:Thema>
			<lev:Themanaam>gas hoge druk</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0881912211</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>false</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_gas+hoge+druk_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_gas+hoge+druk_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
			<lev:ThemaBijlagen>
				<lev:SoortThemaBijlage>profielschets</lev:SoortThemaBijlage>
				<lev:Bijlage>
					<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.Profielschets_gasHogeDruk_Liander_detail_A4_20.pdf</lev:Bestandsnaam>
				</lev:Bijlage>
			</lev:ThemaBijlagen>
		</lev:Themas>
		<lev:Themas>
			<lev:Thema>hoogspanning</lev:Thema>
			<lev:Themanaam>hoogspanning</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0653550024</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>true</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_hoogspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Maatvoering>
				<lev:Bestandsnaam>bronnen/KL0002/MV_hoogspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Maatvoering>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_hoogspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
			<lev:ThemaBijlagen>
				<lev:SoortThemaBijlage>eisVoorzorgsmaatregel</lev:SoortThemaBijlage>
				<lev:Bijlage>
					<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.EV_hoogspanning_15G357840_EVBrief_Liander_model12.pdf</lev:Bestandsnaam>
				</lev:Bijlage>
			</lev:ThemaBijlagen>
		</lev:Themas>
		<lev:Themas>
			<lev:Thema>middenspanning</lev:Thema>
			<lev:Themanaam>middenspanning</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0881912211</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>false</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_middenspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Maatvoering>
				<lev:Bestandsnaam>bronnen/KL0002/MV_middenspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Maatvoering>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_middenspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
		</lev:Themas>
		<lev:Themas>
			<lev:Thema>middenspanning</lev:Thema>
			<lev:Themanaam>datatransport</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0881912211</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>false</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_datatransport_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Maatvoering>
				<lev:Bestandsnaam>bronnen/KL0002/MV_datatransport_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Maatvoering>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_datatransport_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
			<lev:ThemaBijlagen>
				<lev:SoortThemaBijlage>profielschets</lev:SoortThemaBijlage>
				<lev:Bijlage>
					<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.Profielschets_datatransport_Liander_detail_A4_22.pdf</lev:Bestandsnaam>
				</lev:Bijlage>
			</lev:ThemaBijlagen>
		</lev:Themas>
		<lev:Themas>
			<lev:Thema>middenspanning</lev:Thema>
			<lev:Themanaam>gas lage druk</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0881912211</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>false</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_gas+lage+druk_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_gas+lage+druk_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
			<lev:ThemaBijlagen>
				<lev:SoortThemaBijlage>profielschets</lev:SoortThemaBijlage>
				<lev:Bijlage>
					<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.Profielschets_GLD_7344XA21_detail_A4_21.pdf</lev:Bestandsnaam>
				</lev:Bijlage>
			</lev:ThemaBijlagen>
		</lev:Themas>
		<lev:Themas>
			<lev:Thema>middenspanning</lev:Thema>
			<lev:Themanaam>laagspanning</lev:Themanaam>
			<lev:Toezichthouders>
				<lev:Telefoon>0881912211</lev:Telefoon>
			</lev:Toezichthouders>
			<lev:EisVoorzorgmaatregel>false</lev:EisVoorzorgmaatregel>
			<lev:Ligging>
				<lev:Bestandsnaam>bronnen/KL0002/LG_laagspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Ligging>
			<lev:Maatvoering>
				<lev:Bestandsnaam>bronnen/KL0002/MV_laagspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Maatvoering>
			<lev:Annotatie>
				<lev:Bestandsnaam>bronnen/KL0002/AN_laagspanning_Liander_0000574962_15G357840.png</lev:Bestandsnaam>
			</lev:Annotatie>
			<lev:ThemaBijlagen>
				<lev:SoortThemaBijlage>profielschets</lev:SoortThemaBijlage>
				<lev:Bijlage>
					<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.Profielschets_LS_7344XA19_detail_A4_19.pdf</lev:Bestandsnaam>
				</lev:Bijlage>
			</lev:ThemaBijlagen>
		</lev:Themas>
		<lev:Bijlagen>
			<lev:SoortBijlage>algemeen</lev:SoortBijlage>
			<lev:Bijlage>
				<lev:Bestandsnaam>bronnen/KL0002/nl.imkl.KL0002.ALG_Liander_BriefAlgemeen-v1.1_15G357840.pdf</lev:Bestandsnaam>
			</lev:Bijlage>
		</lev:Bijlagen>
		<lev:Bijlagen>
			<lev:SoortBijlage>BL</lev:SoortBijlage>
			<lev:Bijlage>
				<lev:Bestandsnaam>bronnen/KL0002/BL_Liander_0000574962_15G357840_OntwerpContouren.pdf</lev:Bestandsnaam>
			</lev:Bijlage>
		</lev:Bijlagen>
		<lev:Ondergrondkaarten>
